{{- $appName := include "apps.appName" . -}}
{{- $appNamespace := include "apps.appNamespace" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $appName }}-db
  namespace: {{ $appNamespace }}
  labels:
    app: {{ $appName }}-db
spec:
  serviceName: {{ $appName }}-db
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 1Gi
  replicas: 1
  selector:
    matchLabels:
      app: {{ $appName }}-db
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  template:
    metadata:
      labels:
        app: {{ $appName }}-db
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      terminationGracePeriodSeconds: 30
      containers:
        - name: {{ $appName }}-db
          image: mysql:8.0
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          {{- if .Values.dbResources }}
          resources:
            {{- toYaml .Values.dbResources | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.ports.db.container.port }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
              subPath: mysql
          env:
            - name: MYSQL_USER
              value: {{ .Values.env.mysqlUser }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.env.mysqlPassword }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.env.mysqlRootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.env.mysqlDatabase }}