apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mysql_data/
